version: '3.9'

services:
  next:
    container_name: nextv09
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3009:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=auto-gpt.tech"
      - "traefik.http.routers.nextv09-insecure.rule=Host(`chat.t99ltd.info`)"
      - "traefik.http.routers.nextv09-insecure.entrypoints=web"
      - "traefik.http.middlewares.nextv09-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.nextv09-insecure.middlewares=nextv09-redirect-web-secure"
      - "traefik.http.routers.nextv09.rule=Host(`chat.t99ltd.info`)"
      - "traefik.http.routers.nextv09.entrypoints=websecure"
      - "traefik.http.routers.nextv09.tls=true"
      - "traefik.http.routers.nextv09.tls.certresolver=myresolver"
      - "traefik.http.services.nextv09-insecure.loadbalancer.server.port=3000"
      - "traefik.http.routers.nextv09.middlewares=nextv09_auth"
      - "traefik.http.middlewares.nextv09_auth.basicauth.users=DEA:$$2y$$05$$u6owE6I3Hlmnjx6L9GiF0.Txrr022V20vsbKsUpAtWiq0VWlxn.t."
    networks:
      - auto-gpt.tech
      - default
  platform:
    container_name: platform-v09
    build:
      context: ./platform
      target: prod
    ports:
      - "8099:8000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=auto-gpt.tech"
      - "traefik.http.routers.platform-v09-insecure.rule=Host(`backend.t99ltd.info`)"
      - "traefik.http.routers.platform-v09-insecure.entrypoints=web"
      - "traefik.http.middlewares.platform-v09-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.platform-v09-insecure.middlewares=platform-v09-redirect-web-secure"
      - "traefik.http.routers.platform-v09.rule=Host(`backend.t99ltd.info`)"
      - "traefik.http.routers.platform-v09.entrypoints=websecure"
      - "traefik.http.routers.platform-v09.tls=true"
      - "traefik.http.routers.platform-v09.tls.certresolver=myresolver"
      - "traefik.http.services.platform-v09-insecure.loadbalancer.server.port=8000"
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: db
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
    depends_on:
      - db
    networks:
      - auto-gpt.tech
      - default

  db:
    image: mysql:8.0
    container_name: db-nextv09
    restart: always
    build:
      context: ./db
    ports:
      - "3310:3307"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      MYSQL_TCP_PORT: 3307
    volumes:
      - db_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - default

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    restart: on-failure:0
    ports:
      - "8088:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate:/var/lib/weaviate
    networks:
      - default

  docs:
    build: ./docs
    ports:
      - "3005:3001"
    networks:
      - default

volumes:
  weaviate:
  db_data:

networks:
  auto-gpt.tech:
    external: true
